### ISSUE TITLE
NPE Crash `.getTextureAtlasSprite()` on Color rule, ExtraUtils2 compat

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#26]
Sorting chest with some EU2 items and `Color` rule cause crash:
```less
Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$MouseInputEvent$Pre@7850a4f:
java.lang.NullPointerException: null
	at com.rwtema.extrautils2.items.ItemIngredients.getType(ItemIngredients.java:136) ~[ItemIngredients.class:?]
	at com.rwtema.extrautils2.items.ItemIngredients.getTexture(ItemIngredients.java:123) ~[ItemIngredients.class:?]
	at com.rwtema.extrautils2.backend.XUItemFlat.getSprite(XUItemFlat.java:28) ~[XUItemFlat.class:?]
	at com.rwtema.extrautils2.backend.XUItemFlat.getBaseTexture(XUItemFlat.java:42) ~[XUItemFlat.class:?]
	at com.rwtema.extrautils2.backend.model.PassthruModelItem.getParticleTexture(PassthruModelItem.java:190) ~[PassthruModelItem.class:?]
	at com.cleanroommc.bogosorter.common.sort.color.ItemColorHelper.getTextureAtlasSprite(ItemColorHelper.java:166) ~[ItemColorHelper.class:?]
	at com.cleanroommc.bogosorter.common.sort.color.ItemColorHelper.getItemColors(ItemColorHelper.java:81) ~[ItemColorHelper.class:?]
```

No crash log provided, so whole debug.log:
[debug.log.gz](https://github.com/CleanroomMC/InventoryBogoSorter/files/10029783/debug-1.log.gz)

**Comment by brachy84** [comment]
This is there fault and there isnt much i can do about it except wrapping my method with `try catch`
