### ISSUE TITLE
Crash on opening any container

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#49]
Opening containers causing crash. Tested on Draconic Evolution Chest and Rustic's Cabinet and even vanilla chest:
```less
[FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre@5f492f74:
java.lang.ClassCastException: com.brandon3055.draconicevolution.client.gui.GuiDraconiumChest cannot be cast to com.cleanroommc.bogosorter.core.mixin.GuiScreenAccessor
	at com.cleanroommc.bogosorter.common.sort.ButtonHandler.onDrawScreen(ButtonHandler.java:54) ~[ButtonHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2907_ButtonHandler_onDrawScreen_Pre.invoke(.dynamic) ~[?:?]
```

```less
java.lang.ClassCastException: rustic.client.gui.GuiCabinetDouble cannot be cast to com.cleanroommc.bogosorter.core.mixin.GuiScreenAccessor
    at com.cleanroommc.bogosorter.common.sort.ButtonHandler.onDrawScreen(ButtonHandler.java:54)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2909_ButtonHandler_onDrawScreen_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
```

```less
java.lang.ClassCastException: net.minecraft.client.gui.inventory.GuiChest cannot be cast to com.cleanroommc.bogosorter.core.mixin.GuiScreenAccessor
	at com.cleanroommc.bogosorter.common.sort.ButtonHandler.onDrawScreen(ButtonHandler.java:54) ~[ButtonHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2909_ButtonHandler_onDrawScreen_Pre.invoke(.dynamic) ~[?:?]
```

- `bogosorter-1.3.0`
- `modularui-2.1.0`

[debug.log](https://github.com/CleanroomMC/InventoryBogoSorter/files/12616571/debug.log)

**Comment by brachy84** [comment]
WTF

**Comment by KorewaLidesu** [comment]
> WTF

`[mixin]: Critical problem: mixin.bogosorter.json:GuiScreenAccessor from mod unknown-owner target net.minecraft.client.gui.GuiScreen was loaded too early.`

**Comment by brachy84** [comment]
fixed
