### ISSUE TITLE
Crash on pressing [...]

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#50]
I placed Draconic Evolution chest and pressed [...] button:

![image](https://github.com/CleanroomMC/InventoryBogoSorter/assets/936618/8d7ff0a7-fc0d-4ef9-9f2f-b13f18c7fbc6)

- `bogosorter-1.3.0`

```
java.lang.IndexOutOfBoundsException: Index: 251, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:659)
    at java.util.ArrayList.get(ArrayList.java:435)
    at net.minecraft.inventory.Container.slotClick(Container.java:258)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:392)
    at com.brandon3055.brandonscore.client.gui.modulargui_old.ModularGuiContainer.mouseClicked(ModularGuiContainer.java:95)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:533)
    at com.brandon3055.brandonscore.client.gui.modulargui_old.ModularGuiContainer.handleMouseInput(ModularGuiContainer.java:131)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:501)
```

**Comment by brachy84** [comment]
Yeah, that happens when the button is over a slot. I need to check everything i have compat for.
