### ISSUE TITLE
Incompatible with Latest ModularUI (2.3.0)

### ISSUE THREAD

**Issue by mcadventurecity** [CleanroomMC/InventoryBogoSorter#65]
Apologies if this is already being worked on, but it seems that BogoSorter needs to be updated to support ModularUI 2.3.0. The log is saying it currently requires versions below this.

[latest.log](https://github.com/CleanroomMC/InventoryBogoSorter/files/13273174/latest.log)

**Comment by mcadventurecity** [comment]
This is the relevant section:

```
[17:18:33] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MissingModsException: Mod bogosorter (Inventory Bogo Sorter) requires [modularui@[2.2.2,2.3.0)]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:266) ~[Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572) ~[Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:6601) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```
