### ISSUE TITLE
Sorting crash every time `SortHandler.playSortSound`

### ISSUE THREAD

**Issue by Krutoy242** [CleanroomMC/InventoryBogoSorter#73]
Happens not to me but to other player of `E2E-E` modpack.

> It is crashing when using the inventory sort function. Doesn't happen every time but i'd say atleast 50% of the time.

```ruby
java.lang.NullPointerException: Updating screen events
at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:34)
at net.minecraft.client.audio.PositionedSoundRecord.getRecord(SourceFile:18)
at net.minecraft.client.audio.PositionedSoundRecord.getMasterRecord(SourceFile:14)
at com.cleanroommc.bogosorter.common.sort.SortHandler.playSortSound(SortHandler.java:41)
at com.cleanroommc.bogosorter.ClientEventHandler.sort(ClientEventHandler.java:267)
at com.cleanroommc.bogosorter.ClientEventHandler.handleInput(ClientEventHandler.java:199)
at com.cleanroommc.bogosorter.ClientEventHandler.onMouseInput(ClientEventHandler.java:142)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_3018_ClientEventHandler_onMouseInput_Pre.invoke(.dynamic)
```

https://mclo.gs/AY32a3Z

**Comment by brachy84** [comment]
This is probably because of april fools and the scuffed way it was written
