### ISSUE TITLE
Crash when opening/closing Bogo config menu

### ISSUE THREAD

**Issue by ZZZank** [CleanroomMC/InventoryBogoSorter#84]
crash report: https://mclo.gs/WTky1hw
latest.log: https://mclo.gs/7czrwGk

```
Caused by: java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 0
    at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
    at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
    at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
    at java.util.Objects.checkIndex(Objects.java:385)
    at java.util.ArrayList.get(ArrayList.java:427)
    at net.minecraft.inventory.Container.getSlot(Container.java:120)
    at net.minecraft.inventory.Container.putStackInSlot(Container.java:519)
    at net.minecraft.client.network.NetHandlerPlayClient.handleSetSlot(NetHandlerPlayClient.java:1154)
    at net.minecraft.network.play.server.SPacketSetSlot.processPacket(SourceFile:30)
    at net.minecraft.network.play.server.SPacketSetSlot.processPacket(SourceFile:10)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
    at java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 13 more
```

**Comment by brachy84** [comment]
"Giving enough helpful information to help the dev fix the bug"-challange: Impossible

**Comment by ZZZank** [comment]
exactly, in fact I just made a test in an instance with Bogo installed, and I cannot reproduce this issue, so I will need to look for the mod causing this problem in almost 300 mods, practically impossible
